name: credit-scoring
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.2.3
  - numpy=2.2.2
  - seaborn=0.13.2
  - matplotlib=3.10.0
  - scikit-learn=1.6.1
  - streamlit=1.42.0
  - joblib=1.4.2
  - plotly=6.0.0
  - jupyter=1.1.1